### ISSUE TITLE
NoMethodError (undefined method `params_encoder' for {:timeout=>5, :open_timeout=>5}:Hash):

### ISSUE THREAD

**Issue by bzitzow** [dewski/itunes#15]
Hi,

I was just poking around and wanted to do a quick test with your gem. Using the examples in the documentation, I'm getting an error:

```
NoMethodError (undefined method `params_encoder' for {:timeout=>5, :open_timeout=>5}:Hash):
```

Could this be because Faraday has been updated but this gem has not been updated to reflect it's new API?

**Comment by dewski** [comment]
> Could this be because Faraday has been updated but this gem has not been updated to reflect it's new API?

Definitely possible. I haven't used this gem myself in quite a few years. I'll give this a look and if it's a simple fix of upgrading the gem I'll cut a release.

**Comment by openface** [comment]
Just got bit by this too.

**Comment by dewski** [comment]
Pushed v0.7.0 with a fix to Rubygems. Thanks for reporting!
